// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    HeaderBar: typeof import('./src/components/HeaderBar/HeaderBar.vue')['default']
    IconsVue: typeof import('./src/components/HeaderBar/@element-plus/icons-vue.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    ModuleLeft: typeof import('./src/components/Module/ModuleLeft.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/SearchPop/SearchPop.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
