// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HeaderBar: typeof import('./src/components/HeaderBar/HeaderBar.vue')['default']
    IconsVue: typeof import('./src/components/HeaderBar/@element-plus/icons-vue.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    ModuleLeft: typeof import('./src/components/Menu/Menu.vue')['default']
    MusicController: typeof import('./src/components/MusicController/MusicController.vue')['default']
    Precommend: typeof import('./src/components/Recommend/Precommend.vue')['default']
    Recommend: typeof import('./src/components/Recommend/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/SearchPop/SearchPop.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
