// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CommentArea: typeof import('./src/components/Comment/CommentArea.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderBar: typeof import('./src/components/HeaderBar/HeaderBar.vue')['default']
    HighQuality: typeof import('./src/components/highQualityCard/HighQuality.vue')['default']
    ListCard: typeof import('./src/components/ListCard/ListCard.vue')['default']
    ListTable: typeof import('./src/components/ListTable/ListTable.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MusicController: typeof import('./src/components/MusicController/MusicController.vue')['default']
    MusicListBar: typeof import('./src/components/MusicListBar/MusicListBar.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    RecommendSongList: typeof import('./src/components/RecommendSongList/RecommendSongList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/SearchPop/SearchPop.vue')['default']
    SecondNavBar: typeof import('./src/components/SecondNavBar/SecondNavBar.vue')['default']
    SoftBox: typeof import("./src/components/SoftBox/SoftBox.vue")["default"]
    SortBox: typeof import('./src/components/SortBox/SortBox.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    User: typeof import('./src/components/User/User.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
